- src/Makefile
This change looks straight forward but I wonder if the symbolic link of
`rxadm` pointing to `rapiddisk` is still required.
I guess the `rxadm` occurrences could be deleted from the makefile without
any effects as I could not detect any references from within the code.
> replace last two /sbin occurences with $(DIR)

- doc/Makefile
This change introduces the make variable `MAN_DIR` with its current default
of `/usr/share/man/man1`. It allows overriding when setting it as option to
the make command.
Additionally, the `MKDIR` command was extended to create the man directory tree
with appropriate directory permissions (`0755`).
> allow MAN_DIR to be overridden in make command

- src/Makefile
- src/archive.c
- src/common.h
- src/core.c
- src/crypt.c
- src/main.c
I left it as GPLv2+.  You can change it if you want strict GPLv2
> GPLv2+ headers for /src

- module/Makefile
- module/rapiddisk-cache.c
- module/rapiddisk.c
Left both modules as GPLv2 strict.  Used language from Facebook/flashcache_wt.
> GPLv2 headers for /module, based on language from Facebook/flashcache_wt

- Makefile
- module/Makefile
#36 During "make dkms" remove older DKMS installs on current kernel
Now `dkms-install` target is used to check if current rapiddisk version is already installed on current kernel. `dkms-uninstall` uninstalls rapiddisk via dkms (this version from this kernel only)
> Changed the way dkms is installed/removed.

- module/Makefile
Changed the if/else/endif syntax and made some error messages nicer
I changed the `1>&2 2>/dev/null` syntax cause not working well on Ubuntu.
Changed the if/else/endif chains to a cleaner syntax.
Switched to `echo $$?` to check the return code, it is simpler and works well.
I removed `"..."` and final `.` from error messages. The `.` is added by Make.
These changes should be tested on Centos though.
And are really small things!
Bye!
> Really small changes to module/Makefile

- Makefile
- module/Makefile
- module/dkms.conf
- src/Makefile
These four commits change some Makefiles and add missing double quotes in `dkms.conf` file.
The commit messages detail the changes.
Regards
> Makefile changes

- module/rapiddisk-cache.c
- src/net.c
This patch contains
* c23cff7 resolves compilation error for linux kernels >=5.11 (obsoleted `#include <asm/kmap_types.h>`)
I successfully tested on ArchLinux with kernels 5.10.x and 5.11.x
`==> dkms install --no-depmod -m rapiddisk -v 7.1.0 -k 5.11.2-arch1-1`
`==> dkms install --no-depmod -m rapiddisk -v 7.1.0 -k 5.10.19-1-lts`
I hope it doesn't break older kernel compilations :)
> Compilation fix for linux kernels >=5.11

- module/rapiddisk.c
If you send `rapiddisk deatch 0` (or any other disk number that doesn't currently exist), the module triggers a `BUG: unable to handle page fault for address: ...`.
This patch simply returns an error if a disk wasn't found with the provided number.
> Don't BUG when userspace sends an invalid disk num

- scripts/rapiddisk-rootdev/CHANGELOG.md
- scripts/rapiddisk-rootdev/install_initrd.sh
- scripts/rapiddisk-rootdev/ubuntu/rapiddisk_boot
Under Ubuntu, the boot script tried to run `/usr/sbin/rapiddisk_sub` to initialize rapiddisk, but the hook script installs `rapiddisk_sub` in `/sbin`. Under Ubuntu versions > 18 this is not an issue, since `/sbin` is a link to `/usr/sbin`, but on older Ubuntu versions this simply cause `rapiddisk_sub` not to be executed at all. Now the `rapiddisk_sub` script is invoked from `/sbin` and works on old and new Ubuntu.
> Ubuntu 18 fix and minor improvements

- src/cli.h
Buffer overflow fix in NVMe struct (https://github.com/pkoutoupis/rapiddisk/issues/90).
> Buffer overflow fix in NVMe struct.

- pkg/debian/rapiddisk-on-boot.prerm
- pkg/debian/rapiddisk-on-boot_kernel_prerm
- scripts/rapiddisk-rootdev/ubuntu/rapiddisk_clean
Hello,
the `rapiddisk-on-boot.prerm` script uses `bash` arrays, but the hashbang points to `/bin/sh`. This is a **bad bug** since by default `/bin/sh` is symlinked to `/bin/dash`, a shell not supporting arrays. These leads to an error during the package update/removal which can't be resolved. I changed the hashbang to `#!/bin/bash` for that script, this should solve the issue, as long as `bash` is installed.
I changed the `rapiddisk_clean` script too, unfolding the `A && B || C` construct in an `if/then/else` one.
Regards
> Fix a bug in rapiddisk-on-boot.prerm script

- src/daemon.c
- src/main.c
This addresses https://github.com/pkoutoupis/rapiddisk/issues/130 and adds JSON status returns to a few NVMe functions. Again, thank you for finding this. @matteotenca: Once this is merged, we can continue working on the larger mem leak PR you opened.
> Fixed small memory leak and added json status return to NVMe functions.

- src/common.h
- src/nvmet.c
Add a new #define for an error message in common.h. Use scandir_filter_no_dot() filter for scandir() more often.
This is related to an issue in PR #145, as described [here](https://github.com/pkoutoupis/rapiddisk/pull/145#issuecomment-1379388352).
> Fix missing check for port when exporting/unexporting (NVMe)

- src/nvmet.c
In nvmet_export_volume(), nvmet_scan_ports() is called to get the existing port list, but the function does not return all of them. Switched to nvmet_scan_all_ports().
In nvmet_enable_port(), some function calls to free resources were missing.
> Fix a wrong function call and some memory leaks in nvmet.c

- conf/rapiddiskd.service
`ExecstartPre` in `rapiddiskd.service` uses an absolute path to `sh`, `/usr/bin/`, but on some system `sh` is placed in `/bin/`. This causes the service to fail upon start. Removing the absolute path seems to solve.
Fix #156
> Remove absolute path from service file

- src/common.h
- src/json.c
- src/json.h
- src/nvmet.c
- src/utils.c
1. Add the `NVMET_ALLOWED_HOST` struct and put it inside `NVMET_PROFILE`, so that for every NQN there is a corresponding linked list of the hosts which was granted the access.
2. Now `nvmet_scan_subsystem()` fills and adds the allowed hosts in `NVMET_ALLOWED_HOST` to every `NVMET_PROFILE`.
3. Now `nvmet_view_exports()`, in normal - not JSON - mode, prints all the hosts allowed to access each NQN.
4. `nvmet_unexport_volume()` does not delete host dir from `/sys/kernel/config/nvmet/hosts/` if there are other NQN using that dir.
5. `free_nvmet_linked_lists()` now frees the memory allocated for the `NVMET_ALLOWED_HOST` linked lists too.
> Fix some nvmet_unexport_volume() issues and improve NVMET_PROFILE struct

- pkg/debian/changelog
- pkg/debian/control
- src/nvmet.c
- src/nvmet.h
1. Changed `Build-Depends` in `control` to adapt to the new dependency's relations between `dkms` and `dh-dkms` starting with Ubuntu 22.10 Kinetic.
2. Fixed the `changelog`.
3. Added `check_nvmet_subsystem()` function to verify whether the NVMe kernel modules were loaded.
> Fix 'pkg/debian/changelog' and 'pkg/debian/control'

- src/Makefile
- src/common.h
- src/main.c
- src/utils.c
- src/utils.h
As per feature request #176, now it is possible to specify a number followed by B/KiB/KB/MiB/MB/GiB/GB. If the specified size will result in a value < 1048576 Bytes, an error will be raised.
> Allow human-readable notation for sizes in command line (B/KB/KiB) etc.

- module/rapiddisk.c
- src/rapiddiskd.h
this patch originates from the Ubuntu package
Fixes: #190
> Linux 6.11 support
